server:
  port: 8080
spring:
  application.name: itil-api
  datasource:
    url: @url@
    driverClassName: org.h2.Driver
    username: test
    password: test
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: false

  jpa:
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true