server:
  port: 8080
  
spring:
  application.name: itil-api
  datasource:
    driverClassName: org.postgresql.Driver
    password: 7Xci9WE3kMecD8dIIh0JrxPUjixJODFO
    url: jdbc:postgresql://dpg-cd6p722rrk04votcdv5g-a.ohio-postgres.render.com:5432/itildb
    username: itil

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
        ddl-auto: update